app:
  activation_url: "http://localhost:8000"
  authentication_url: "http://localhost:8000"

server:
  port: 8000

jwt:
  secret: "secret"
  token_expiration_time: 3600
  refresh_token_expiration_time: 86400
  activation_token_expiration_time: 86400
  authentication_token_expiration_time: 900

database:
  host: "localhost"
  port: 5432
  user: "eskept"
  password: "password"
  db_name: "dev_database"
  ssl_mode: "disable"

cache:
  host: "localhost"
  port: 6379

smtp:
  host: "smtp.localhost"
  port: 587
  email: "admin@localhost.com"
  password: "password"
  
template:
  email_activation: "templates/email/activation.html"
  email_authentication: "templates/email/authentication.html"
  email_reset_password: "templates/email/reset_password.html"
